image: node:10.15.0
definitions: 
  caches:
    - node
  services: 
    mongo: 
      image: mongo
  step: &BuildAndTest
    name: Build & Test
    script:
      - yarn
      - yarn run build
      - yarn run test
    services: 
      - mongo

pipelines:
  default:
    - step: *BuildAndTest
    - step:
        name: Create artifact
        script:
          - tar czfv application.tgz pom.xml dist/
        artifacts:
          - application.tgz
    - step:
        name: Deploy to staging Heroku pipeline from Artifacts
        deployment: staging
        script:
        - pipe: atlassian/heroku-deploy:1.1.2
          variables:
            HEROKU_API_KEY: $HEROKU_API_KEY
            HEROKU_APP_NAME: $HEROKU_APP_NAME
            ZIP_FILE: "application.tgz"
  branches:
    master:
      - step:
          name: "Deploy to Production"
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PRODUCTION_HEROKU_APP_NAME.git HEAD:master
    develop:
      - step:
          name: "Deploy to Staging"
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$STAGING_HEROKU_APP_NAME.git HEAD:master
      - step:
          name: "Trigger Deploy to Production"
          trigger: manual
          script:
            - git checkout master
            - git merge develop
            - git push origin master
  pull-requests:
    feature/*:
      - step: *BuildAndTest