stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - bundle install --path /cache
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec rake test

staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=gitlab-ci-ruby-test-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master

production:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=gitlab-ci-ruby-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - tags


# gitlab-runner register \
#   --non-interactive \
#   --url "https://gitlab.com/" \
#   --registration-token "PROJECT_REGISTRATION_TOKEN" \
#   --description "ruby:2.6" \
#   --executor "docker" \
#   --docker-image ruby:2.6 \
#   --docker-services latest